<?php

/**
 * @file
 * Primary module hooks for Celabrate module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_views_data_alter().
 */
function celebrate_views_data_alter(array &$data) {
  $data['node_field_data']['node_type_filter'] = [
    'title' => t('Enhanced node type filter'),
    'filter' => [
      'title' => t('Enhanced node type filter'),
      'help' => t('Provides a custom filter for nodes by their type.'),
      'field' => 'type',
      'id' => 'string'
    ]
  ];

  $data['node_field_data']['nodes_titles'] = [
    'title' => t('Node titles'),
    'filter' => [
      'title' => t('Node titles'),
      'help' => t('Specify a list of titles a node can have'),
      'field' => 'title',
      'id' => 'd8views_node_titles'
    ]
  ];
}
